from flask import Flask, request, jsonify
from flask_cors import CORS
import nltk
import re
from werkzeug.utils import secure_filename
import os

nltk.download("punkt")

app = Flask(__name__)
CORS(app)  # Allow cross-origin requests

UPLOAD_FOLDER = "uploads"
os.makedirs(UPLOAD_FOLDER, exist_ok=True)
app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER

# Section Keywords for Better Parsing
SECTION_HEADERS = [
    "Abstract", "Introduction", "Literature Review", "Methodology", "Results", "Conclusion"
]

# Parse text into sections based on recognized headers
def parse_sections(text):
    sections = {header: "" for header in SECTION_HEADERS}
    current_section = None

    for line in text.splitlines():
        line = line.strip()

        # Identify section headers (case-insensitive)
        for header in SECTION_HEADERS:
            if re.match(rf"^{header}", line, re.IGNORECASE):
                current_section = header
                break

        # Append content to the current section
        if current_section:
            sections[current_section] += line + " "

    return sections

# Generate LaTeX IEEE Template
def generate_ieee_latex(sections):
    title = "Automated IEEE Paper Formatting Using AI"
    author = "Generated by AI"

    ieee_template = f"""
    \\documentclass[conference]{{IEEEtran}}
    \\usepackage{{cite}}
    \\usepackage{{graphicx}}
    \\usepackage{{amsmath,amssymb,amsfonts}}
    \\usepackage{{algorithmic}}
    \\usepackage{{hyperref}}
    \\usepackage{{array}}
    \\usepackage{{url}}

    \\title{{{title}}}

    \\author{{{author}}}

    \\begin{{document}}

    \\maketitle

    % Abstract Section
    \\begin{{abstract}}
    {sections.get("Abstract", "Abstract content is missing.")}
    \\end{{abstract}}

    % Keywords
    \\begin{{IEEEkeywords}}
    IEEE paper format, automated formatting, natural language processing (NLP), research automation
    \\end{{IEEEkeywords}}

    % Introduction Section
    \\section{{Introduction}}
    {sections.get("Introduction", "Introduction content is missing.")}

    % Literature Review Section
    \\section{{Literature Review}}
    {sections.get("Literature Review", "Literature Review content is missing.")}

    % Methodology Section
    \\section{{Methodology}}
    {sections.get("Methodology", "Methodology content is missing.")}

    % Results Section
    \\section{{Results and Discussion}}
    {sections.get("Results", "Results content is missing.")}

    % Conclusion Section
    \\section{{Conclusion}}
    {sections.get("Conclusion", "Conclusion content is missing.")}

    % References Section
    \\begin{{thebibliography}}{{99}}
        \\bibitem{{ieeeexample}} IEEE, "IEEE Editorial Style Manual," 2023.
        \\bibitem{{latex}} Leslie Lamport, "LaTeX: A Document Preparation System," Addison-Wesley, 1994.
        \\bibitem{{nlp}} Jurafsky & Martin, "Speech and Language Processing," Pearson, 2021.
    \\end{{thebibliography}}

    \\end{{document}}
    """
    return ieee_template

@app.route("/upload", methods=["POST"])
def upload_file():
    """
    Receives a text file, processes it, and returns formatted IEEE content.
    """
    if "file" not in request.files:
        return jsonify({"error": "No file part"}), 400

    file = request.files["file"]

    if file.filename == "":
        return jsonify({"error": "No selected file"}), 400

    if file:
        filename = secure_filename(file.filename)
        filepath = os.path.join(app.config["UPLOAD_FOLDER"], filename)
        file.save(filepath)

        # Read and parse the uploaded file
        with open(filepath, "r", encoding="utf-8") as f:
            raw_text = f.read()

        # Extract and structure sections
        sections = parse_sections(raw_text)

        # Generate IEEE-formatted LaTeX output
        ieee_formatted_text = generate_ieee_latex(sections)

        return jsonify({"formatted_text": ieee_formatted_text})

if __name__ == "__main__":
    app.run(debug=True)


